# NumPy Basics: Array Creation, Indexing, and Slicing

### Concept: What is NumPy?
NumPy (Numerical Python) is the foundational library for scientific computing in Python. The core of NumPy is the **ndarray** (N-dimensional array), a highly optimized, fast data structure used for numerical operations. 

Unlike standard Python lists, NumPy arrays:
1.  Are **homogeneous**: They hold elements of the *same* data type (usually numbers).
2.  Are **fast**: Operations are written in C, making them mathematically much faster.
3.  Support **vectorization**: You can perform operations on whole arrays without writing `for` loops.

In [1]:
import numpy as np

# 1. Creating Arrays from Python Lists
my_list = [1, 2, 3, 4, 5]
array_1d = np.array(my_list)
print("1D Array:\n", array_1d)

# 2. Creating 2D Arrays (Matrices)
my_matrix = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
array_2d = np.array(my_matrix)
print("\n2D Array:\n", array_2d)

# Checking attributes
print("\nArray Shape:", array_2d.shape)  # Number of rows and columns (2, 3)
print("Data Type:", array_2d.dtype)      # Type of values inside (float64)
print("Number of Dimensions:", array_2d.ndim) # 2

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1. 2. 3.]
 [4. 5. 6.]]

Array Shape: (2, 3)
Data Type: float64
Number of Dimensions: 2


### Built-in Array Generators
Instead of converting lists, you often create arrays directly using NumPy's built-in functions.

In [ ]:
# Create an array of zeros (shape is passed as a tuple)
zeros = np.zeros((3, 4))
print("Zeros:\n", zeros)

# Create an array of ones
ones = np.ones((2, 2))
print("\nOnes:\n", ones)

# Like python's range(), but returns an array: np.arange(start, stop, step)
sequence = np.arange(0, 10, 2)
print("\nArange:", sequence)

# Returns evenly spaced numbers over a specified interval: np.linspace(start, stop, num_of_points)
linear_space = np.linspace(0, 1, 5)
print("\nLinspace:", linear_space)

# Random numbers (between 0 and 1)
random_arr = np.random.rand(2, 2)
print("\nRandom:\n", random_arr)

### Indexing and Slicing

Just like Python lists, you can retrieve items by their index (starting at 0). For 2D matrices, you pass two indices: `array[row_index, col_index]`.

**Slicing syntax:** `array[start:stop:step]`

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing 1D
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing 1D
print("Slice [1:4]:", arr[1:4])  # Elements at index 1, 2, 3 (exclusive 4)

# 2D Array Slicing
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

print("\nFull matrix:\n", matrix)

# Grab row 1, column 2 (0-indexed)
print("\nElement at [1, 2]:", matrix[1, 2]) # Should be 30

# Grab the entire first row
print("First row:", matrix[0, :])

# Grab the entire second column
print("Second column:", matrix[:, 1])

# Grab a sub-matrix (top 2 rows, first 2 columns)
print("Sub-matrix:\n", matrix[0:2, 0:2])

### 🤖 AI/ML Connection: Why Data Scientists use NumPy Arrays over Lists
Pandas DataFrames and PyTorch/TensorFlow Tensors are built explicitly to mimic and act like NumPy arrays under the hood. When you do "Computer Vision", an image is nothing more than a 3D NumPy array (Height x Width x ColorChannels). 
When you need to crop an image to just the top-right corner to feed into your image classifier, you literally just use NumPy slicing: `cropped_img = image[0:100, 100:200, :]`

### 💥 Gotcha: Memory Views vs Copies (Crucial!)
Unlike standard Python lists, slicing a NumPy array returns a **view**, not a new array. Modifying the slice WILL modify the original array! This is done for memory efficiency (so slicing large datasets doesn't instantly double your RAM usage).

In [ ]:
# The View Gotcha
original = np.array([1, 2, 3, 4, 5])
slice_of_arr = original[0:3]

slice_of_arr[0] = 999 

# Oh no! The original is altered!
print(original) # Outputs [999, 2, 3, 4, 5]

# How to fix it? Explicitly use .copy()
original = np.array([1, 2, 3, 4, 5])
safe_copy = original[0:3].copy()
safe_copy[0] = 999

print(original) # Outputs [1, 2, 3, 4, 5] - Safe!

### 📋 Cheat Sheet
* **Imports**: `import numpy as np`
* **Creation**: `np.array([list])`, `np.zeros((shape))`, `np.ones((shape))`, `np.arange(start, stop, step)`, `np.linspace(start, stop, num_items)`
* **Attributes**: `arr.shape` (dimensions), `arr.dtype` (data type), `arr.ndim` (number of axes).
* **Indexing 1D**: `arr[index]`
* **Indexing 2D**: `arr[row_index, col_index]`
* **Slicing**: `arr[start:stop:step]`
* **Copying**: `arr.copy()` (Mandatory to avoid view-modification gotcha).